name: CI-CD-Pipeline
env:
  EB_ENVIRONMENT: "Notification-Dev"

on:
  release:
    types:
      - published

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone repository
        uses: actions/checkout@v1

      - name: Test echo  
        run: |
          APP_NAME="$(echo ${{github.ref}}" | grep -E -i -w -o 'api|sms|email')"
          echo "$APP_NAME"
          echo "$APP_NAME"
          echo "$APP_NAME"
          echo "${{env.EB_ENVIRONMENT}}-$APP_NAME"