name: Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        id: create_release
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
